#!/bin/env sh

alias ap="ansible-playbook"
alias dcup="docker compose up -d"
alias dcdown="docker compose down"
alias dcexec="docker compose exec" 
alias dclogs="docker compose logs"
alias ls="lsd"
alias cat="bat"

#Display docker ps with most important things (less output)
docker() {
	#Set docker binary, it depends on some distros and other oses like MacOs. 
	if [[ -f /usr/bin/docker ]]; then
	 	docker=/usr/bin/docker
	elif [[ -f /usr/local/bin/docker ]]; then
		docker=/usr/local/bin/docker
	else
		echo "Docker binary not found, unfunction this function" 
		return 1
	fi
	
	#Custom Docker functions, fallback to docker binary if no expression matches
	if [[ $1 == "yeet" && $# == 1 ]]; then
		$docker stop $($docker ps -aq) && $docker rm $($docker ps -aq)
	elif [[ $1 == "yeet" && $2 == "-f" ]]; then
		$docker stop $($docker ps -aq) 2> /dev/null
		$docker rm $($docker ps -aq) 2> /dev/null
		$docker system prune -f 2> /dev/null
	else
		$docker "$@"
	fi
	unset docker
}

#Use up 3 instead of cd ../../../ or cd ../; cd ../; cd ../
up() { 
	local x=''
	for i in $(seq ${1:-1})
	do 
		x="$x../"
	done;
	cd $x; 
}

