- hosts: all
  become: true

  tasks:

    - name: Install essential programs
      apt:
        name: vim, nmap, net-tools, ncat, ncdu, rsync, mariadb-client, htop, wget
        update_cache: yes
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
    - name: Copy shell utils 
      copy: 
        src: ../files/shell_goodies
        dest: /etc/ansible_shell_goodies
        mode: 0664
        owner: root
        group: adm
    
    - name: Add shell utils to user's bashrc
      blockinfile:
        path: /home/{{ ansible_user|default("szymon") }}/.bashrc
        content: "source /etc/ansible_shell_goodies"

    - name: Add shell utils to root's bashrc
      blockinfile:
        path: /root/.bashrc
        content: "source /etc/ansible_shell_goodies"
    
    - name: Add user {{ ansible_user|default("szymon") }} to needed groups
      user:
        name: '{{ ansible_user|default("szymon") }}'
        groups: docker, adm, backup, sudo
        append: yes

    - name: Copy vimrc to {{ ansible_user|default("szymon") }}'s directory
      copy:
        src: ../files/vimrc
        dest: /home/{{ ansible_user|default("szymon") }}/.vimrc
        mode: 0664
        owner: '{{ ansible_user|default("szymon") }}'
        group: '{{ ansible_user|default("szymon") }}'

    - name: Copy vimrc to root's directory
      copy:
        src: ../files/vimrc
        dest: /root/.vimrc
        mode: 0664
        owner: root
        group: root
    
