---
- hosts: all
  name: Customize swappiness
  become: true

  tasks: 
  - name: Add swappiness to sysctl  
    ansible.posix.sysctl:
      name: vm.swappiness
      value: '5'
      state: present
      sysctl_file: /etc/sysctl.d/80-custom.conf
      reload: true
